In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.3'

In [6]:
result = 0
for i in range(101):
    result+=i
print(result)

5050


In [13]:
l=list(range(11))
l


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
type(l)

list

In [15]:
l2=[str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [16]:
type(l2)

list

In [17]:
type(l[0])

int

In [18]:
type(l2[0])

str

In [19]:
l3 = [True, "school", 3.14, 43]
[type(i) for i in l3]
 

[bool, str, float, int]

In [21]:
# Fixed-typed Arrays in Python, for stroing data in efficient , fixed-typed data buffers
import array
a = array.array('i',l)
a
# However, numpy array provide more useful operations on this data.

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [22]:
# creating ndarray from python lists
nl= np.array(l)
nl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
type(nl)

numpy.ndarray

In [25]:
nl3 = np.array(l3) # will give error, or np will upcast the int to float 
nl3

array(['True', 'school', '3.14', '43'], dtype='<U32')

In [26]:
type(nl3)

numpy.ndarray

In [27]:
# we can specify the type of our np array
nldtype= np.array(l, dtype='float32')
nldtype

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [28]:
# multi
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [29]:
np.zeros((2,3), dtype="int32")


array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [34]:
np.ones((3,4), dtype=float)*3.14

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [42]:
che=np.linspace(0,10,5)
che

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.random.randn(10)

array([-0.28118522, -0.44392921, -0.68941414, -0.29421253, -0.02405795,
       -0.48282421, -0.56316642,  0.42729084,  1.54070913,  1.10368876])

In [40]:
np.random.randint(0,100,(3,2))

array([[88,  8],
       [55,  5],
       [32, 19]])

In [44]:
np.random.choice(che)

0.0

In [45]:
np.random.normal(0,10,(4,3))

array([[ -3.24563722,   6.3922189 , -18.77902207],
       [ 11.66889879, -13.76258129,  -5.53072877],
       [ -4.62505099,   2.92421548,  -1.78970218],
       [ -7.44462643,  -2.74344896,   2.03728955]])

In [49]:
np.eye(3)*-1

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]])

In [51]:
chk=np.empty((3,4))
chk

array([[ 3.24563722,  6.3922189 , 18.77902207, 11.66889879],
       [13.76258129,  5.53072877,  4.62505099,  2.92421548],
       [ 1.78970218,  7.44462643,  2.74344896,  2.03728955]])

In [52]:
chk

array([[ 3.24563722,  6.3922189 , 18.77902207, 11.66889879],
       [13.76258129,  5.53072877,  4.62505099,  2.92421548],
       [ 1.78970218,  7.44462643,  2.74344896,  2.03728955]])

In [54]:
type(chk)

numpy.ndarray

In [56]:
np.empty(10)

array([0.28118522, 0.44392921, 0.68941414, 0.29421253, 0.02405795,
       0.48282421, 0.56316642, 0.42729084, 1.54070913, 1.10368876])

In [58]:
# dtypes 
np.empty((3,2),dtype=np.int16)

array([[257, 257],
       [257, 257],
       [257, 257]], dtype=int16)

In [59]:
np.empty((3,2), dtype='int16')

array([[-19424,    909],
       [ 15704,     48],
       [    16,      0]], dtype=int16)